# Generated by Django 4.2.26 on 2025-12-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255, unique=True)),
                ("grna_map", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source_doi", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Product",
                "db_table": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "product_tags",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=255, unique=True)),
                (
                    "tag_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "tags",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "functional_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="功能摘要(英文)"
                    ),
                ),
                (
                    "embedding_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="向量基准文本"
                    ),
                ),
                (
                    "vector",
                    models.TextField(help_text="JSON array of embedding floats"),
                ),
                (
                    "model_name",
                    models.CharField(default="S-PubMedBert-MS-MARCO", max_length=100),
                ),
                ("dim", models.IntegerField(default=768)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="search_engine.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_embeddings",
                "managed": True,
            },
        ),
    ]
