# Generated by Django 4.2.26 on 2025-12-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doi", models.CharField(max_length=255, verbose_name="论文DOI")),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="文件名/来源名",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="search_engine.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "文献来源",
                "verbose_name_plural": "文献来源",
                "db_table": "product_sources",
                "managed": True,
            },
        ),
    ]
