# Generated by Django 6.0.3 on 2026-03-23 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0002_productsource"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubChemTag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tag_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "tag_category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="标签类别"
                    ),
                ),
                (
                    "pubchem_classification",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="PubChem分类",
                    ),
                ),
                (
                    "mesh_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="MeSH ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "PubChem标签",
                "verbose_name_plural": "PubChem标签",
                "db_table": "pubchem_tags",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["tag_category"], name="pubchem_tag_tag_cat_6077bd_idx"
                    ),
                    models.Index(
                        fields=["pubchem_classification"],
                        name="pubchem_tag_pubchem_1b88d3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="YeastPubChemData",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pubchem_data",
                        serialize=False,
                        to="search_engine.product",
                    ),
                ),
                (
                    "pubchem_cid",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="PubChem CID"
                    ),
                ),
                (
                    "iupac_name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="IUPAC名称"
                    ),
                ),
                (
                    "functional_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="功能描述(PubChem)"
                    ),
                ),
                (
                    "sync_failed",
                    models.BooleanField(default=False, verbose_name="同步失败"),
                ),
                (
                    "sync_failed_reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="失败原因"
                    ),
                ),
                (
                    "last_sync_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后同步尝试时间"
                    ),
                ),
                (
                    "last_sync_success",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后成功同步时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "PubChem数据",
                "verbose_name_plural": "PubChem数据",
                "db_table": "yeast_pubchem_data",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["pubchem_cid"], name="yeast_pubch_pubchem_564346_idx"
                    ),
                    models.Index(
                        fields=["sync_failed"], name="yeast_pubch_sync_fa_cfd004_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductPubChemTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "confidence_score",
                    models.FloatField(default=1.0, verbose_name="置信度"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pubchem_api", "PubChem API"),
                            ("manual", "手动"),
                            ("ai", "AI分析"),
                        ],
                        default="pubchem_api",
                        max_length=50,
                        verbose_name="来源",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="search_engine.product",
                    ),
                ),
                (
                    "pubchem_tag",
                    models.ForeignKey(
                        db_column="pubchem_tag_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="search_engine.pubchemtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品PubChem标签关联",
                "verbose_name_plural": "产品PubChem标签关联",
                "db_table": "product_pubchem_tags",
                "managed": True,
                "unique_together": {("product", "pubchem_tag")},
            },
        ),
    ]
