# Generated by Django 6.0.3 on 2026-03-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0003_pubchemtag_yeastpubchemdata_productpubchemtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yeastpubchemdata",
            name="pubchem_cid",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="PubChem CID"
            ),
        ),
    ]
