# Generated by Django 6.0.3 on 2026-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0004_alter_yeastpubchemdata_pubchem_cid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yeastpubchemdata",
            name="iupac_name",
            field=models.TextField(blank=True, null=True, verbose_name="IUPAC名称"),
        ),
    ]
