# Generated by Django 6.0.3 on 2026-03-31 14:03

from django.db import migrations, models


def migrate_existing_data(apps, schema_editor):
    """将现有数据从旧字段迁移到新解耦字段"""
    ProductEmbedding = apps.get_model('search_engine', 'ProductEmbedding')
    Product = apps.get_model('search_engine', 'Product')
    YeastPubChemData = apps.get_model('search_engine', 'YeastPubChemData')

    total = ProductEmbedding.objects.count()
    print(f"开始迁移 {total} 条 ProductEmbedding 记录...")

    migrated_count = 0
    for embedding in ProductEmbedding.objects.all().select_related('product'):
        try:
            # 1. 迁移 functional_summary 到 function 字段
            if embedding.functional_summary and not embedding.function:
                embedding.function = embedding.functional_summary

            # 2. 从 ManyToMany tags 关系生成 tags_text
            if not embedding.tags_text:
                # 需要通过历史模型获取标签关系
                product = embedding.product
                # 使用prefetch_related需要特殊处理，这里直接查询关联表
                tags_info = []
                # 通过历史模型的tags关系获取
                for tag in product.tags.all():
                    tag_text = tag.tag_name
                    if tag.tag_category:
                        tag_text = f"{tag_text} ({tag.tag_category})"
                    tags_info.append(tag_text)
                if tags_info:
                    embedding.tags_text = "; ".join(tags_info)

            # 3. 迁移 grna_map 到 grna 字段
            if product.grna_map and not embedding.grna:
                embedding.grna = product.grna_map

            # 4. 迁移 PubChem 数据
            try:
                pubchem_data = YeastPubChemData.objects.get(product=product)
                if pubchem_data.iupac_name and not embedding.iupac_name:
                    embedding.iupac_name = pubchem_data.iupac_name
                if pubchem_data.functional_description and not embedding.pubchem_description:
                    embedding.pubchem_description = pubchem_data.functional_description
            except YeastPubChemData.DoesNotExist:
                pass  # 没有PubChem数据

            # 5. 设置 source_database
            if not embedding.source_database:
                try:
                    pubchem_data = YeastPubChemData.objects.get(product=product)
                    if pubchem_data.pubchem_cid:
                        embedding.source_database = 'PubChem'
                    else:
                        embedding.source_database = 'Manual'
                except YeastPubChemData.DoesNotExist:
                    embedding.source_database = 'Manual'

            # 6. 更新 embedding_text（调用模型方法）
            embedding.update_embedding_text()
            embedding.save(update_fields=[
                'function', 'tags_text', 'grna', 'iupac_name',
                'pubchem_description', 'source_database', 'embedding_text'
            ])

            migrated_count += 1
            if migrated_count % 100 == 0:
                print(f"已迁移 {migrated_count}/{total} 条记录...")

        except Exception as e:
            print(f"迁移记录 {embedding.id} 时出错: {e}")
            continue

    print(f"迁移完成！成功迁移 {migrated_count}/{total} 条记录。")


def reverse_migration(apps, schema_editor):
    """回滚迁移：将数据从新字段移回旧字段（仅用于回滚）"""
    # 注意：functional_summary字段在反向迁移时会被重新添加
    # 但通常不需要实现完整的回滚，因为这是破坏性重构
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0005_alter_yeastpubchemdata_iupac_name"),
    ]

    operations = [
        # 第一步：添加所有新字段
        migrations.AddField(
            model_name="productembedding",
            name="function",
            field=models.TextField(blank=True, null=True, verbose_name="功能描述"),
        ),
        migrations.AddField(
            model_name="productembedding",
            name="grna",
            field=models.TextField(blank=True, null=True, verbose_name="gRNA信息"),
        ),
        migrations.AddField(
            model_name="productembedding",
            name="iupac_name",
            field=models.TextField(blank=True, null=True, verbose_name="IUPAC名称"),
        ),
        migrations.AddField(
            model_name="productembedding",
            name="pubchem_description",
            field=models.TextField(blank=True, null=True, verbose_name="PubChem描述"),
        ),
        migrations.AddField(
            model_name="productembedding",
            name="source_database",
            field=models.CharField(
                choices=[
                    ("PubChem", "PubChem"),
                    ("Manual", "Manual Entry / Local"),
                    ("UniProt", "UniProt"),
                    ("KEGG", "KEGG Pathway"),
                ],
                default="Manual",
                max_length=20,
                verbose_name="来源数据库",
            ),
        ),
        migrations.AddField(
            model_name="productembedding",
            name="tags_text",
            field=models.TextField(blank=True, null=True, verbose_name="标签文本"),
        ),
        # 第二步：执行数据迁移
        migrations.RunPython(migrate_existing_data, reverse_migration),
        # 第三步：删除旧字段
        migrations.RemoveField(
            model_name="productembedding",
            name="functional_summary",
        ),
    ]
