# Generated by Django 6.0.3 on 2026-04-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("search_engine", "0006_remove_productembedding_functional_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagCategorySystem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_path",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="分类路径"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="显示名称"),
                ),
                ("level", models.IntegerField(verbose_name="层级")),
                (
                    "parent_path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="父级路径"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("general", "普通标签"),
                            ("pubchem", "PubChem标签"),
                            ("both", "两者均可"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="适用标签类型",
                    ),
                ),
                (
                    "example_tags",
                    models.TextField(blank=True, null=True, verbose_name="示例标签"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "标签分类",
                "verbose_name_plural": "标签分类系统",
                "db_table": "tag_category_system",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["category_path"], name="tag_categor_categor_4257a7_idx"
                    ),
                    models.Index(fields=["level"], name="tag_categor_level_1f7e5e_idx"),
                    models.Index(
                        fields=["tag_type"], name="tag_categor_tag_typ_8b4f6c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TagHierarchy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "parent_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="父标签ID"
                    ),
                ),
                (
                    "child_object_id",
                    models.PositiveIntegerField(verbose_name="子标签ID"),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("parent_child", "父子关系"),
                            ("synonym", "同义词"),
                            ("related", "相关关系"),
                            ("brother", "兄弟关系"),
                        ],
                        default="parent_child",
                        max_length=50,
                        verbose_name="关系类型",
                    ),
                ),
                ("confidence", models.FloatField(default=1.0, verbose_name="置信度")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai_analysis", "AI分析"),
                            ("pubchem_api", "PubChem API"),
                            ("manual", "手动添加"),
                            ("rule_based", "规则匹配"),
                        ],
                        default="ai_analysis",
                        max_length=50,
                        verbose_name="来源",
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="层次级别")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_tag_hierarchies",
                        to="contenttypes.contenttype",
                        verbose_name="子标签类型",
                    ),
                ),
                (
                    "parent_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_tag_hierarchies",
                        to="contenttypes.contenttype",
                        verbose_name="父标签类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "标签层次关系",
                "verbose_name_plural": "标签层次关系",
                "db_table": "tag_hierarchies",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["parent_content_type", "parent_object_id"],
                        name="tag_hierarc_parent__d887a9_idx",
                    ),
                    models.Index(
                        fields=["child_content_type", "child_object_id"],
                        name="tag_hierarc_child_c_b19b9c_idx",
                    ),
                    models.Index(
                        fields=["relationship_type"],
                        name="tag_hierarc_relatio_86de1a_idx",
                    ),
                    models.Index(fields=["level"], name="tag_hierarc_level_a15848_idx"),
                ],
                "unique_together": {
                    (
                        "parent_content_type",
                        "parent_object_id",
                        "child_content_type",
                        "child_object_id",
                    )
                },
            },
        ),
    ]
