# Generated by Django 6.0.3 on 2026-04-21 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0007_tagcategorysystem_taghierarchy"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tag_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "tag_category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="标签类别"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "手工标签"),
                            ("pubchem_api", "PubChem API"),
                            ("ai", "AI分析"),
                        ],
                        default="manual",
                        max_length=50,
                        verbose_name="来源",
                    ),
                ),
                (
                    "original_tag_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="原始标签ID"
                    ),
                ),
                (
                    "original_source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual_tag", "手工标签"),
                            ("pubchem_tag", "PubChem标签"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="原始标签类型",
                    ),
                ),
                (
                    "pubchem_classification",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="PubChem分类",
                    ),
                ),
                (
                    "mesh_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="MeSH ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "统一标签",
                "verbose_name_plural": "统一标签",
                "db_table": "unified_tags",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["tag_name"], name="unified_tag_tag_nam_6fcfda_idx"
                    ),
                    models.Index(
                        fields=["tag_category"], name="unified_tag_tag_cat_1d172e_idx"
                    ),
                    models.Index(
                        fields=["source"], name="unified_tag_source_f84340_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnifiedProductTagMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "confidence_score",
                    models.FloatField(default=1.0, verbose_name="置信度"),
                ),
                (
                    "original_mapping_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="原始关联ID"
                    ),
                ),
                (
                    "original_source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual_mapping", "手工关联"),
                            ("pubchem_mapping", "PubChem关联"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="原始关联类型",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search_engine.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="tag_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search_engine.unifiedtag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "统一产品标签关联",
                "verbose_name_plural": "统一产品标签关联",
                "db_table": "unified_product_tag_mapping",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["product", "tag"], name="unified_pro_product_261a67_idx"
                    ),
                    models.Index(
                        fields=["confidence_score"],
                        name="unified_pro_confide_607962_idx",
                    ),
                ],
                "unique_together": {("product", "tag")},
            },
        ),
    ]
