# Generated by Django 4.2.26 on 2025-12-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "managed": False,
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productembedding",
            options={
                "verbose_name": "Product Embedding",
                "verbose_name_plural": "Product Embeddings",
            },
        ),
        migrations.AlterModelOptions(
            name="producttag",
            options={
                "managed": False,
                "verbose_name": "Product-Tag Relation",
                "verbose_name_plural": "Product-Tag Relations",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "managed": False,
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
