# Generated by Django 4.2.26 on 2025-12-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0002_alter_product_options_alter_productembedding_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productembedding",
            name="product",
        ),
        migrations.RemoveField(
            model_name="producttag",
            name="product",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="ProductEmbedding",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductTag",
        ),
    ]
